/*

About EcmaScript : (ES)

"ES1" 
-in 1997, the first version, ECMAScript 1, was standardized and released, and then a third version.

"ES2" "ES3" 
-The second version never really quite happened, but the third version came out in 1999 with some minor changes and fixes.

"ES4" "ES5"
-in 2009, they released ECMAScript 5, and ECMAScript 4 was scrapped.
-"JavaScript is going to be the scripting language for the web".
- In 2009 is when JavaScript became King of the web because all of the major players agreed that this is going to be the scripting language, the programming language of the web. 
-They built in a lot of features. There's a lot that's built into ECMAScript 5 that we'll be using throughout this course.

"ES6"
-In 2015, ES6, what is commonly referred to as ES6, was released, sometimes it's called ECMAScript 2015. These two terms are interchangeable, but ES6 was released and it's a big release, a lot changed and a lot was added, and a lot of JavaScript has been more powerful and turned into a more general all purpose programming language.
-A lot of what you'll be learning in this course are pieces from the 2009 ECMAScript 5 standard and pieces from the ECMAScript 2015 ES6 standard together, which really make up the major part of JavaScript.

"ES7" "ES8"
-Since 2015, the standardizing body has been in a nice cadence of releasing new versions each year. From then on, instead of calling it ES7 and ES8 and that kind of stuff, they stuck with the year. They came out with ECMAScript 2016, ECMAScript 2017, and so on and so forth. 
-In each year there are smaller new additions added, but on the whole, these additions are fairly small and they are being more advanced pieces but we will be doing a lot with ECMAScript 5 and ES6 or ECMAScript 2015.
*/