//----------------------------------------(1) declaring variable

var x = ""; //assigns it an empty string.
var chesse = "yummy";
var age = 23;

//-----------------------------------(2) variables are case sensitive
/*
var 1cat = ""; //name can't start from number
var $cat = ""; //$ is used by libraries
var my-cat = ""; //- is used for minus -> it thinks you try to subtract cat from my which is not work
var my cat = ""; // space is not allowed in name
var new = ""; //new is keyword in JS

var cat
var CAT 
var Cat
var myCate //camelCase name
this all are different variables.
*/