//--------------------------------------------------ex1
/*
var x = ""; //assigns it an empty string.
var chesse = "yummy";
var age = 23;

console.log(x);
console.log(chesse);
console.log(age);
*/ 

//--------------------------------------------------ex2
/*
console.log(myNum);  //undefined
var myNum = 5;
console.log(myNum);  //5

console.log(myOtherNum);  //reference error : myOtherNum is not defined
myOtherNum = 6;
console.log(myOtherNum);  //6
*/

//---------------------------------------------------ex3
var num1 = 5;
//now in console if I tap enter after this first it will return undefined. bcz num1 is var.

num2 = 6;
//now in console if I tap enter after this it will return direct ans. bcz num2 is autoPredict type.


//---------------------------------------------------ex4
console.log(num1+num2); //11